---
name: Exception-Base
version: 0.2202
author:
  - 'Piotr Roszatycki <dexter@cpan.org>'
abstract: Lightweight exceptions
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Exception-Base
  license: http://dev.perl.org/licenses/
  repository: http://dexter-cpan.googlecode.com/svn/Exception-Base
build_requires:
  Test::Unit::Lite: 0.12
requires:
  perl: 5.006
configure_requires:
  Module::Build: 0.34
provides:
  Exception::Base:
    file: lib/Exception/Base.pm
    version: 0.2202
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
