---
name: Exception-Base
version: 0.1901
author:
  - 'Piotr Roszatycki <dexter@debian.org>'
abstract: Lightweight exceptions
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.006
provides:
  Exception::Base:
    file: lib/Exception/Base.pm
    version: 0.1901
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
